name: Release

on:
  push:
    tags:
    - v*

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:

    - uses: nowsprinting/check-version-format-action@v3
      id: version
      with:
        prefix: 'v'
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.version.outputs.full }}
        release_name: ${{ steps.version.outputs.full }}
        draft: false
        prerelease: false
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: sperjar/coscmd:${{ steps.version.outputs.full_without_prefix }}
